name: Extract and Update Data

on:
  push:
    branches:
      - main  # Replace with your default branch if different

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run the extraction script
        run: node extract_and_update.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add updated_August.json
          git commit -m 'Update August data with extracted content'
          git push origin HEAD:main  # Ensure this matches your default branch